### ISSUE TITLE
Bedrock functions may start with "HIDE"

### ISSUE THREAD

**Issue by Nixinova** [Arcensoth/language-mcfunction#43] opened 2021-02-13 04:32 UTC
### **Bug report checklist**
- [x] The language-mcfunction extension only provides syntax highlighting. Have you confirmed that your issue is with the syntax highlighting, and **not** other features such as squiggly underlines, warning indicators, and/or pop-ups?
- [x] Ensure that you are able to reproduce the issue without any other datapack-related extensions enabled.
- [x] Make sure you attach a screenshot to your bug report. Bug reports without a screenshot will be closed.

## Description

From [the MC wiki page for Bedrock functions](https://minecraft.gamepedia.com/Function_(Bedrock_Edition)):
> If the first line of the function is `HIDE` (excluding any commented lines), then the function is not visible in the suggestions for the function command, but can still be called by typing the command manually.

However, syntax highlighting marks "HIDE" on the first line as invalid:

![image](https://user-images.githubusercontent.com/42429413/107841302-c64de500-6e1e-11eb-8ac2-67d51ff257de.png)

Only the second line should be marked invalid.

I have tested this feature in-game and the keyword does indeed work.

**Comment by Arcensoth** [comment] 2021-02-23 04:30
This is such a narrow-minded and poorly-designed feature on Mojang's part, I'm still in partial disbelief it's a real thing.

Note that this is a version-agnostic grammar that is, by design, completely unaware of what commands exist and what arguments they expect. All it knows is that each line of a function is either blank, a comment, or begins with a literal token (lower-case word). From there, it attempts to distinguish tokens separately based on the characters they are composed of.

The reason `HIDE` is being highlighted as an error is because Mojang has introduced never-before-seen syntax to mcfunction: capital letters at the beginning of a line. Just like most other things in the grammar, I don't think it makes sense to attempt to decide whether any given `HIDE` is invalid at all. Instead, just incorporate capital letters into the grammar somewhere so they can be classified instead of cause errors.

A straightforward and adaptable solution might be to add a new 4th type of root token: an effective fallback that just captures anything else composed of alphanumeric characters at the beginning of a line and classifies it separately. This would immediately solve `HIDE` being highlighted as invalid, and would also account for any other similarly-designed atrocities that Mojang might happen to implement in the future.

**Comment by Arcensoth** [comment] 2021-02-23 14:46
> I have tested this feature in-game and the keyword does indeed work.

Now, I know you said you tested this, but...

> [...] I'm still in partial disbelief it's a real thing.

@Nixinova Have you by chance tested to check whether the `HIDE`den function still exists at all? Some people are claiming that this is not a real feature and the only reason it hides the function is because it causes a syntax error and invalidates the entire thing. There's been a lot of confusion about the legitimacy of this feature.

**Comment by Nixinova** [comment] 2021-02-23 18:20
Yes I'm pretty sure the function did work when I ran it, I can try again though.

**Comment by Nixinova** [comment] 2021-02-23 18:29
Similar discussion is at https://github.com/Blockception/VSCode-Bedrock-Development-Extension/pull/40

**Comment by Arcensoth** [comment] 2021-02-23 19:12
> Similar discussion is at [Blockception/VSCode-Bedrock-Development-Extension#40](https://github.com/Blockception/VSCode-Bedrock-Development-Extension/pull/40)

Thanks for the link. That thread furthers my suspicions that this is indeed not supported and the functions are most likely being invalidated entirely.

Note that the blurb from the wiki is no longer present, and apparently there's no *official* documentation for this. So far as I can tell, there's no evidence that it works either.

I'm going to close this, but I'll keep it in mind in case it ever becomes a real thing with official documentation and proof that it is stable and supported.

~~For now, I'm just glad it's not real.~~

**Closed** 2021-02-23 19:20 UTC

**Comment by minerj101** [comment] 2021-02-24 20:31
> > Similar discussion is at [Blockception/VSCode-Bedrock-Development-Extension#40](https://github.com/Blockception/VSCode-Bedrock-Development-Extension/pull/40)
> 
> Thanks for the link. That thread furthers my suspicions that this is indeed not supported and the functions are most likely being invalidated entirely.
> 
> Note that the blurb from the wiki is no longer present, and apparently there's no _official_ documentation for this. So far as I can tell, there's no evidence that it works either.
> 
> I'm going to close this, but I'll keep it in mind in case it ever becomes a real thing with official documentation and proof that it is stable and supported.
> 
> ~For now, I'm just glad it's not real.~

It is real, im planning on making a pack that it works
Ive just been busy

The hide isn't capital its just 

hide

**Comment by tryashtar** [comment] 2021-02-24 20:37
![image](https://user-images.githubusercontent.com/26075577/109062629-66b8ca80-76a5-11eb-8bf3-7b8397b595f3.png)

**Comment by minerj101** [comment] 2021-02-24 20:45
[
[hide_proof.zip](https://github.com/Arcensoth/language-mcfunction/files/6038757/hide_proof.zip)
](url)

**Comment by tryashtar** [comment] 2021-02-24 20:53
You're using format version 1 in the manifest, which is the legacy behavior where Bedrock just skips invalid commands instead of failing to load the entire function. In that format version, you can replace `hide` with literally any invalid text and the remaining commands will still run. I guess the autocomplete hiding is just a side effect.

**Comment by minerj101** [comment] 2021-02-24 20:57
> You're using format version 1 in the manifest, which is the legacy behavior where Bedrock just skips invalid commands instead of failing to load the entire function. In that format version, you can replace `hide` with literally any invalid text and the remaining commands will still run. I guess the autocomplete hiding is just a side effect.

I use an old format because I use  
https://3t3.me/others/manifest_gen/
It works with this template
That is not a problem

Yes, it will still run because it is a valid syntax. also, if it is flagged as a error the function will still run, it just won't include the line with the problematic function.

**Comment by tryashtar** [comment] 2021-02-24 21:03
So to sum up:
* Format version 1 allows functions with invalid commands to load
* `hide` is nothing special, any invalid command will do
* They don't show up in autocomplete, but can still be run from chat
* Format version 2 fixes all of this

**Comment by DaanV2** [comment] 2021-02-24 21:31
Also to show that it's not perse the keyword `hide`

I tried the following:

![image](https://user-images.githubusercontent.com/2393905/109068331-00a56500-76f0-11eb-857d-bc4caafd13fd.png)

Still worked, it's indeed Minecraft just skipping over it.

**Comment by minerj101** [comment] 2021-02-24 23:51
strange

**Comment by DaanV2** [comment] 2021-02-25 00:04
sorry I dont know atm.

I also don't recommend supporting it, as it uses a bug to use this.

You could try moving unwanted functions to an internal folder and use obscured filenames

**Comment by minerj101** [comment] 2021-02-25 02:12
Well it would still show up in the function list and be messy. The reason it disappears is that it isn't syntax.
