### ISSUE TITLE
Support for non-namespaced resource locations

### ISSUE THREAD

**Issue by RedBones48** [Arcensoth/language-mcfunction#18] opened 2019-03-30 14:28 UTC
setblock ~ ~ ~ chest[type=type]{some nbt} shows up as a error. The blockstate and or with nbt shows up as error.

**Comment by Arcensoth** [comment] 2019-04-01 05:03
What version of the extension are you running? There was a bug like this that was fixed a while back.

Blockstate and NBT seem to be working fine on the latest release (v0.12.0):

![image](https://i.imgur.com/V3Yzcdg.png)

And the current release being used by GitHub Linguist (v0.10.0 I think):

![image](https://i.imgur.com/x7GWJM3.png)

https://github.com/Arcensoth/language-mcfunction/blob/master/tests/block_predicate.mcfunction#L16

Otherwise, assuming you're running the latest release: do you have a screenshot or exact code snippet you can share so I can diagnose further?

**Comment by Arcensoth** [comment] 2019-04-01 05:07
I think the issue might be with blocks that do not include a namespace. But I'd like to get a screenshot/snippet to confirm my suspicion.

**Comment by Arcensoth** [comment] 2019-04-02 20:28
Confirmed:

![image](https://i.imgur.com/PtKBZtI.png)

**Comment by Arcensoth** [comment] 2019-04-02 20:45
This will likely not be supported for the version-agnostic grammar due to the number of ambiguities vs the recommended approach of including a namespace in resource locations.

However resource locations without namespaces will be supported just fine in the version-specific grammars, because these grammars will know exactly which arguments are supposed to be resource locations and so there will be no problems with ambiguity.

Closing and re-labeling as a "planned feature" for the version-specific grammars.

**Comment by Arcensoth** [comment] 2019-09-20 05:34
Re-opening to contemplate support for the version-agnostic grammar. Maybe I can do something sneaky with look-ahead...

**Comment by Arcensoth** [comment] 2019-09-20 05:52
Support is viable for block predicates with a block state mapping present, otherwise it's ambiguous with an NBT path.

![image](https://user-images.githubusercontent.com/1885643/65302501-5c59df00-db49-11e9-92ec-825576b1536d.png)

**Comment by Arcensoth** [comment] 2019-09-20 05:53
Woops, just realized this issue was for resource locations in general. I'll put things back the way they were.

**Comment by Arcensoth** [comment] 2019-09-21 20:07
This has already been implemented in the form of a "resource ID" parser in the version-specific grammar.

**Closed by Arcensoth** 2019-09-21 20:07 UTC
Labels: enhancement
